#!/bin/bash

echo "This script expects Ubuntu Server 20.04.2 LTS (Focal Fossa)"
echo "Will install all dependencies, libraries, Rstudio and needed packages to run Atlantis and analyze output"

sudo timedatectl set-timezone America/Los_Angeles

sudo apt-get update -y
sudo apt-get dist-upgrade -y

sudo apt-get -y --no-install-recommends install \
    autoconf \
    automake \
    libcurl4 \
    libcurl4-openssl-dev \
    curl \
    gdal-bin \
    flip \
    libcairo2 \
    libharfbuzz-dev \
    libfribidi-dev \
    libcairo-5c0 \
    libapparmor1 \
    libhdf5-dev \
    libnetcdf-dev \
    libxml2-dev \
    libproj15 \
    libssl-dev \
    libv4l-0 \
    libgeotiff5 \
    libglu1-mesa-dev \
    libpoppler-cpp-dev \
    libprotobuf-dev \
    librsvg2-dev \
    libx11-dev \
    lsscsi \
    openjdk-8-jdk \
    python2 \
    proj-bin \
    proj-data \
    protobuf-compiler \
    htop \
    openssl \
    rpm \
    mesa-common-dev \
    netcdf-bin \
    ntp \
    ntpdate \
    subversion \
    texlive-latex-extra \
    nco \
    cdo
 
#https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system
#https://stackoverflow.com/questions/60759865/error-when-installing-sf-in-r-double-free-or-corruption
#to remove a respository https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file

sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev -y
   
sudo add-apt-repository -y ppa:opencpu/jq
sudo apt-get update -qq
sudo apt-get install libjq-dev -y

sudo apt-get -f install -y # missing dependencies
sudo apt autoremove -y #unused packages

echo "Install R"
#http://cran.rstudio.com/bin/linux/ubuntu/
# update indices
sudo apt update -qq
# install two helper packages we need
sudo apt install --no-install-recommends software-properties-common dirmngr
# add the signing key (by Michael Rutter) for these repos
# To verify key, run gpg --show-keys /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc 
# Fingerprint: E298A3A825C0D65DFD57CBB651716619E084DAB9
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
# add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
sudo apt install --no-install-recommends r-base

echo "Install R studio" 

sudo apt-get install gdebi-core -y
wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2022.12.0-353-amd64.deb
sudo gdebi rstudio-server-2022.07.1-554-amd64.deb

echo "Install AzCopy" 

wget -O azcopy_linux_amd64_10.16.2.tar https://aka.ms/downloadazcopy-v10-linux
tar -xzf azcopy_linux_amd64_10.16.2.tar
sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/

if [ -d $HOME/bin ]; then
PATH=$PATH:$HOME/bin
fi
