#!/bin/bash

echo "This script expects Ubuntu Server 24.04.1 LTS (Noble Numbat)"
echo "Will install all dependencies, libraries, Rstudio and needed packages to run Atlantis and analyze output"

sudo apt-get update -y
sudo apt-get dist-upgrade -y

#use to install Conda
#sudo add-apt-repository ppa:deadsnakes/ppa
# sudo apt-get -y install python3.11
 

sudo apt-get install software-properties-common
sudo apt-get -y --no-install-recommends install \
    autoconf \
    automake \
    build-essential \
    libcurl4 \
    libcurl4-openssl-dev \
    curl \
    cargo \
    gdal-bin \
    flip \
    libcairo2 \
    libavfilter-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libcairo-5c0 \
    libapparmor1 \
    libhdf5-dev \
    libnetcdf-dev \
    libudunits2-dev \
    libuv1-dev \
    libxml2-dev \
    libssl-dev \
    libv4l-0 \
    libgeotiff5 \
    libglu1-mesa-dev \
    libpoppler-cpp-dev \
    libprotobuf-dev \
    librsvg2-dev \
    libx11-dev \
    lsscsi \
    openjdk-8-jdk \
    proj-data \
    protobuf-compiler \
    htop \
    openssl \
    rpm \
    mesa-common-dev \
    netcdf-bin \
    ntp \
    ntpdate \
    texlive-latex-extra \
    nco \
    cdo \
    unzip \
    gfortran
 
#use this to install Proj4 which is required for Atlantis 
#https://gist.github.com/robinkraft/2a8ee4dd7e9ee9126030
#http://grasswiki.osgeo.org/wiki/Compile_and_Install_Ubuntu#PROJ4
#uninstall   proj-bin libproj-dev if present
#look for proj with locate libproj.so
# sudo apt install mlocate
#cd /usr/include/libxml2 && sudo cp -R libxml/ ../

#this proj installation solves the error "configure: error: cannot guess build type; you must specify one"
#That specific error happens because the config.guess and config.sub scripts packaged inside PROJ 4.8.0 are from ~2012. 
#They are so old that they literally don't recognize modern 64-bit Linux architectures used by Ubuntu 24.04.

# 1. Install GNU autotools helpers
sudo apt update
sudo apt install -y autotools-dev build-essential

make
sudo make install
sudo ldconfig
sudo apt-get install -y subversion make

cd /tmp
svn co http://svn.osgeo.org/metacrs/proj/branches/4.8/proj/ --non-interactive --trust-server-cert-failures unknown-ca,cn-mismatch,expired,not-yet-valid,other
cd /tmp/proj/nad
sudo wget http://download.osgeo.org/proj/proj-datumgrid-1.5.zip

unzip -o -q proj-datumgrid-1.5.zip

# 2. Go to your proj directory
cd /tmp/proj 

# 3. Overwrite the ancient build scripts with Ubuntu 24.04's modern versions
cp -f /usr/share/misc/config.guess .
cp -f /usr/share/misc/config.sub .

# 4. Configure with legacy C flags and compile
./configure CFLAGS="-O2 -std=gnu89 -w"
 
#these might be needed to install spatial R programs but can conflict with Atlantis proj4

#https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system
#https://stackoverflow.com/questions/60759865/error-when-installing-sf-in-r-double-free-or-corruption
#to remove a respository https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file
#sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
#sudo apt-get update -y
#sudo apt-get upgrade -y
#sudo apt-get dist-upgrade -y
#sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev -y
  
#sudo add-apt-repository -y ppa:opencpu/jq
#sudo apt-get update -qq
#sudo apt-get install libjq-dev -y

sudo apt-get -f install -y # missing dependencies
sudo apt autoremove -y #unused packages

sudo apt-get update
sudo apt-get upgrade

echo "Install R"
sudo apt-get install r-base -y

echo "Install Rstudio" 

sudo apt-get install gdebi-core -y
wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2025.09.1-401-amd64.deb
sudo gdebi rstudio-server-2025.09.1-401-amd64.deb

echo "Install AZ copy" 

#to uninstall azcopy use https://github.com/MicrosoftDocs/azure-docs/issues/18771
wget -O azcopy_windows_amd64_10.30.1 https://aka.ms/downloadazcopy-v10-linux
tar -xzf azcopy_windows_amd64_10.30.1
sudo cp ./azcopy_linux_amd64_*/azcopy /usr/bin/

echo "Install AzCLI"

sudo apt-get update -y
sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y 

sudo mkdir -p /etc/apt/keyrings
curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
  gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
sudo chmod go+r /etc/apt/keyrings/microsoft.gpg

AZ_DIST=$(lsb_release -cs)
echo "Types: deb
URIs: https://packages.microsoft.com/repos/azure-cli/
Suites: ${AZ_DIST}
Components: main
Architectures: $(dpkg --print-architecture)
Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources

sudo apt-get update
sudo apt-get install azure-cli
    
sudo apt-get update
if [ -d $HOME/bin ]; then
PATH=$PATH:$HOME/bin
fi
